[FROGGER-2] Created class and methods
teclamat/frogger_game pull request #14
Opened 2019-05-16 11:35 UTC by Oposq

Please review

2019-05-16 11:37 UTC, kseksalk21 commented
NICEE

2019-05-16 11:39 UTC, teclamat requested changes

2019-05-16 11:39 UTC, teclamat commented on frogger.js
> +
Something's missing here, maybe... `constructor()`?

2019-05-16 11:40 UTC, teclamat requested changes

2019-05-16 11:40 UTC, teclamat commented on frogger.js
> +class Frogger{
Missing space before braces

2019-05-22 10:31 UTC, Oposq commented
Please review once more time

2019-05-22 10:31 UTC, teclamat approved these changes

2019-05-22 10:31 UTC, merged